version: "3.9"

services:
  app:
    container_name: frontend-dev
    build:
      context: .
      target: development
    volumes:
      - ./app:/app
    env_file: ./.env
    ports:
      - ${NODE_LOCAL_PORT}:${NODE_DOCKER_PORT}
    networks:
      - frontend
      - backend

  #backend:
  #  container_name: backend-dev
  #  build:
  #    context: back
  #    target: builder
  #  restart: always
  #  env_file: ./.env
  #  extra_hosts:
  #    - "host.docker.internal:host-gateway"
  #  networks:
  #    - backend
  #  ports:
  #    - ${FLASK_LOCAL_PORT}:${FLASK_DOCKER_PORT}

  nginx:
    container_name: nginx-server
    image: nginx:1.29.3
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - frontend
    depends_on:
      - app

networks:
  frontend:
  backend:
